version: '3'
services:
  # the alexandria server
  alexandria:
    image: huygensing/alexandria-markup-server:latest
    ports:
      - 8002:8080
      - 8003:8081
    environment:
      - BASE_URI=http://192.168.99.100:8002

  # the tex-util server, which can convert the LaTeX from the alexandria server to SVG)
  latex:
    image: huygensing/tex-util-server:latest
    ports:
      - 8000:8080
      - 8001:8081
    depends_on:
      - alexandria
    environment:
      - BASE_URI=http://192.168.99.100:8000

  # the relevant notebooks and python code to connect to the alexandria and latex services
  notebook:
    image: huygensing/alexandria-markup-notebook:latest
    ports:
      - 80:8888
    depends_on:
      - latex
      - alexandria
    volumes:
      - /c/Users/bramb/work:/work
